name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/reactjs-app .

      - name: Publsh image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/reactjs-app:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/reactjs-app:latest

      - name: Delete Old Container
        run: docker rm -f reactContainer
        
      - name: Run docker container
        run: docker run -d -p 3000:80 --name reactContainer ${{ secrets.DOCKER_USERNAME }}/reactjs-app
