name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Source
        uses: actions/checkout@v4

      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '20.x'
      #     cache: 'npm'

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/reactjs-app .

      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/reactjs-app:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Delete Old Container
        run: docker rm -f reactContainer

      - name: Delete Old Image
        run : docker rmi -f ${{ secrets.DOCKER_USERNAME }}/reactjs-app:latest
        
      # - name: Pull image from docker hub
      #   run: docker pull ${{ secrets.DOCKER_USERNAME }}/reactjs-app:latest

      - name: Run docker container & Set auto restart after reboot instance
        run: docker run --restart=unless-stopped -d -p 3000:80 --name reactContainer ${{ secrets.DOCKER_USERNAME }}/reactjs-app
